services:
    ds_bpm.http.client:
        class: GuzzleHttp\Client

    ds_bpm.service:
        abstract: true
        arguments:
            - '@ds_bpm.http.client'

    ds_bpm.collection.api:
        class: Ds\Component\Bpm\Collection\ApiCollection

    ds_bpm.api.factory:
        class: Ds\Component\Bpm\Bridge\Symfony\Bundle\Api\Factory
        arguments:
            - '@ds_bpm.collection.api'
            - '@ds_config.service.config'
